In the previous lesson, we understood more about creating our own modules. We also saw that Python has a library NumPy that allows functionality like adding vectors more easily. In this lesson, we will understand more about this very useful NumPy package.

NumPy is used for a variety of numerical computation tasks. We will explore various aspects of NumPy in this lesson.

### Concept of a Datatype in NumPy Arrays

We have previously seen lists. How would an `array' of data in a list vary from an `array' of data in NumPy. Let us explore through a brief example

Consider that we create a list with numbers in Python using Lists. We could do that easily as follows:

In [37]:
a = [10,35,60,12,23]
print (a);

[10, 35, 60, 12, 23]


Now, we obtain a number that updates the third number in the list to be 43.6 instead of 60. We can update this as follows:

In [38]:
a[2] = 43.3
print(a);

[10, 35, 43.3, 12, 23]


Note that this list has now a mixed set of data types. That is some of the numbers are integers and others are floating point numbers. Once we do computation on these, we may get varying kind of results. That is, lists in Python do not enforce type safety. 

In [39]:
print(type(a[1]));

<class 'int'>


In [40]:
print(type(a[2]));

<class 'float'>


Let us try out the same exercise in NumPy using arrays

In [41]:
import numpy as np
b = np.array([10,35,60,11,23])
print(b);

[10 35 60 11 23]


In [42]:
b[2] = 43.3
print(b)

[10 35 43 11 23]


We observe that in NumPy, the number maintains the data type, i.e. integers for the array and converts 43.3 to 43. We can inspect the datatype of the array element as follows:

In [43]:
print(b.dtype)

int64


This indicates that the array created is an integer array. Similarly, we could create floating point arrays

In [44]:
f = np.array([2.4,3.5,23.6,34])
print(f)

[ 2.4  3.5 23.6 34. ]


In [45]:
print(f.dtype)

float64


In [46]:
f[2] = 23
print(f)

[ 2.4  3.5 23.  34. ]


We can see that the function automatically converts the integer 23 to a floating point number. Thus NumPy provides some amount of type safety in numerical computation. It helps ensure that our computations are consistent. 

### Creation of Arrays

There are several ways to create arrays in Python. These can be created by converting existing lists or tuples in Python or other ways such as by using methods available in NumPy for creating arrays

As we have already observed, we can convert Python lists to NumPy arrays. For instance

In [47]:
a = np.array([4, 2, 5],dtype=float)
print(a)
a = np.array([[4,5, 6],[1,2,3],[7,8,9]])
print(a)
a = np.array([[1+2j, 2],(2+3j, 4 )] ) # mixing tuples and lists
print(a)

[4. 2. 5.]
[[4 5 6]
 [1 2 3]
 [7 8 9]]
[[1.+2.j 2.+0.j]
 [2.+3.j 4.+0.j]]


The examples above show various ways for creating NumPy arrays by converting existing Python data structures. However, there are a number of other functions available to create arrays in NumPy that we will consider

In [49]:
a = np.zeros([3,3])
print(a)
a = np.ones([2, 3])
print(a)
a = np.arange(5)
print(a)
a = np.linspace(2,4, 6)
print(a) # Creates an array between the range 2 and 4 with 6 elements equally spaced

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2 3 4]
[2.  2.4 2.8 3.2 3.6 4. ]


More information about creating arrays can be obtained from the NumPy documentation available at the following [link](https://numpy.org/doc/stable/reference/routines.array-creation.html)